---
- hosts: nodes
  remote_user: ansible
  vars_files:
    - ../../vars/lesson2.yml

  tasks:

  - name: Create new Users
    user:
      name: "{{ item.name }}"
      shell: /bin/bash
      comment: "{{ item.name }}@epam.com"
      password: "{{ item.pass | password_hash('sha512') }}"
      update_password: on_create
    with_items: "{{new_users}}"
###

