---
    - name: install Apache
      yum: 
        name: httpd
        state: latest
      # notify: 
      #   - start firewalld  

    - name: install Firewalld
      yum: 
        name: firewalld
        state: latest
      # notify: 
      #   - start apache  

    - name: start apache 
      service:
        name: httpd
        state: started      

    # - name: start firewalld
    #   service:
    #     name: firewalld
    #     state: reloaded


    - name: start firewalld
      service:
        name: firewalld
        state: restarted                         

    - name: service state httpd
      command: systemctl status httpd
      register: result
      ignore_errors: yes

      # sudo systemctl enable firewalld.service
    
    - name: open {{port_firewalld}} port
      firewalld: 
        port: "{{port_firewalld}}"
        permanent: false 
        state: enabled
      # notify: 
      #   - restart firewalld
      #   - restart apache    

    - name: create file
      copy:
        content: 'Welcome to my web server PRACTICE 3'
        dest: "{{path_html}}"