---
    - name: install Apache
      yum: 
        name: httpd
        state: latest
      notify: 
        - start apache 

    - name: install Firewalld
      yum: 
        name: firewalld
        state: latest
      notify: 
        - start firewalld                  
    
    - name: open {{port_firewalld}} port
      firewalld: 
        port: "{{port_firewalld}}"
        permanent: false 
        state: enabled

    - name: create file
      copy:
        content: 'Welcome to my web server PRACTICE 3'
        dest: "{{path_html}}"