---
- hosts: nodes
  remote_user: ansible
  vars_files:
    - ../../vars/lesson1.yml
  
  tasks: 
    - name: install Apache
      yum: 
        name: httpd
        state: latest

    - name: install Firewalld
      yum: 
        name: firewalld
        state: latest

    - name: start service Apache 
      service:
        name: httpd
        state: started

    - name: service state httpd
      command: systemctl status httpd
      register: result
      ignore_errors: yes
    
    - block:

      - name: start service Firewalld
        service:
          name: firewalld
          state: started

      - name: open {{port_firewalld}} port
        firewalld: 
          port: "{{port_firewalld}}"
          permanent: false 
          state: enabled

      - name: create file
        copy:
           content: 'Welcome to my web server'
           dest: "{{path_html}}"
      when: not result.failed
###
