---
- hosts: nodes
  remote_user: ansible
  vars_files:
    - ../../vars/lesson1.yml

  tasks:

    - name: Remove httpd
      yum:
        name: httpd
        state: absent

    - name: Remove file index.html
      file:
        path: "{{path_html}}"
        state: absent    

    - name: Close 80 port
      firewalld:
        port: "{{port_firewalld}}"
        permanent: false
        immediate: true
        state: disabled
